# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7e0e8422a691e5e424fe6f4a28bdfc7bbb0dd5b9dcdf14111cbc661ef3a600ac86719aa842e42d737b9a26d2f09bcaab6cb76b5aaea38d30aa6b1e67f21e44a

test:
  secret_key_base: 1d67751f3b95b5c93fceda18958dc0d3b9cae111feeea0d7d4aea32d0e8a897d581c66ffc284e3cad4f826f17d95bf594ea72ff28bf123b4a362605d89f28f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
